### ISSUE TITLE
Mojo/Mandelbrot benchmark

### ISSUE THREAD

**Issue by ev-br** [Quansight-Labs/numpy_pytorch_interop#156]
Tracking the progress of running the Mojo Mandelbrot benchmark, https://shashankprasanna.com/benchmarking-modular-mojo-and-pytorch-torch.compile-on-mandelbrot-function/index.html

With pytorch-nightly wheel `'2.1.0.dev20230610+cpu'`, which hopefully includes the fixes for https://github.com/pytorch/pytorch/issues/101980 and https://github.com/pytorch/pytorch/issues/101979, there's still an InternalDynamoError:

```
In [36]: import torch_np as tnp
    ...: 
    ...: @torch.compile
    ...: def mandelbrot_tnumpy(max_iter=200):
    ...:     # Define the boundaries of the complex plane
    ...:     xn = 450
    ...:     yn = 375
    ...:     xmin = -2.25
    ...:     xmax = 0.75
    ...:     ymin = -1.25
    ...:     ymax = 1.25
    ...: 
    ...:     # Create the grid of complex numbers
    ...:     x_values = tnp.linspace(xmin, xmax, xn, dtype=float)
    ...:     y_values = tnp.linspace(ymin, ymax, yn, dtype=float)
    ...:     rx, iy = tnp.meshgrid(x_values, y_values, indexing='xy')
    ...: 
    ...:     x = rx.copy()
    ...:     y = iy.copy()
    ...:     mask = tnp.zeros_like(x)
    ...:     for i in range(max_iter):
    ...:         x_prev = x
    ...:         y_prev = y
    ...:         x = x_prev**2 - y_prev**2 + rx
    ...:         y = 2*x_prev*y_prev + iy
    ...:         inside = tnp.sqrt(x**2 + y**2) <= 2
    ...:         mask+=inside
    ...:     return mask
    ...: 

In [37]: mandelbrot_tnumpy()
---------------------------------------------------------------------------
InternalTorchDynamoError                  Traceback (most recent call last)
Cell In[37], line 1
----> 1 mandelbrot_tnumpy()

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py:295, in _TorchDynamoContext.__call__.<locals>._fn(*args, **kwargs)
    293 dynamic_ctx.__enter__()
    294 try:
--> 295     return fn(*args, **kwargs)
    296 finally:
    297     set_eval_frame(prior)

Cell In[36], line 14, in mandelbrot_tnumpy(max_iter)
     11 ymax = 1.25
     13 # Create the grid of complex numbers
---> 14 x_values = tnp.linspace(xmin, xmax, xn, dtype=float)
     15 y_values = tnp.linspace(ymin, ymax, yn, dtype=float)
     16 rx, iy = tnp.meshgrid(x_values, y_values, indexing='xy') 

Cell In[36], line 24, in <resume in mandelbrot_tnumpy>(___stack0, max_iter, yn, ymin, ymax)
     22 x_prev = x
     23 y_prev = y
---> 24 x = x_prev**2 - y_prev**2 + rx
     25 y = 2*x_prev*y_prev + iy
     26 inside = tnp.sqrt(x**2 + y**2) <= 2

File ~/sweethome/proj/scipy/torch_np_compat/torch_np/_ndarray.py:85, in create_method.<locals>.f(*args, **kwargs)
     84 def f(*args, **kwargs):
---> 85     return fn(*args, **kwargs)

File ~/sweethome/proj/scipy/torch_np_compat/torch_np/_normalizations.py:213, in normalizer.<locals>.normalizer_inner.<locals>.wrapped(*args, **kwds)
    201     args = (
    202         tuple(
    203             maybe_normalize(arg, parm)
   (...)
    206         + args[len(params.values()) :]
    207     )
    209 kwds = {
    210     name: maybe_normalize(arg, params[name]) if name in params else arg
    211     for name, arg in kwds.items()
    212 }
--> 213 result = func(*args, **kwds)
    215 # keepdims
    216 bound_args = None

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py:448, in catch_errors_wrapper.<locals>.catch_errors(frame, cache_size, frame_state)
    445             return hijacked_callback(frame, cache_size, hooks, frame_state)
    447 with compile_lock:
--> 448     return callback(frame, cache_size, hooks, frame_state)

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py:527, in convert_frame.<locals>._convert_frame(frame, cache_size, hooks, frame_state)
    525 counters["frames"]["total"] += 1
    526 try:
--> 527     result = inner_convert(frame, cache_size, hooks, frame_state)
    528     counters["frames"]["ok"] += 1
    529     return result

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py:127, in wrap_convert_context.<locals>._fn(*args, **kwargs)
    125 cleanup = setup_compile_debug()
    126 try:
--> 127     return fn(*args, **kwargs)
    128 finally:
    129     cleanup.close()

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py:360, in convert_frame_assert.<locals>._convert_frame_assert(frame, cache_size, hooks, frame_state)
    345 initial_deterministic_algorithms_state = (
    346     torch.are_deterministic_algorithms_enabled()
    347 )
    349 signpost_event(
    350     "dynamo",
    351     "_convert_frame_assert._compile",
   (...)
    357     },
    358 )
--> 360 return _compile(
    361     frame.f_code,
    362     frame.f_globals,
    363     frame.f_locals,
    364     frame.f_builtins,
    365     compiler_fn,
    366     one_graph,
    367     export,
    368     export_constraints,
    369     hooks,
    370     frame,
    371     frame_state=frame_state,
    372 )

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/utils.py:180, in dynamo_timed.<locals>.dynamo_timed_inner.<locals>.time_wrapper(*args, **kwargs)
    178 with torch.profiler.record_function(f"{key} (dynamo_timed)"):
    179     t0 = time.time()
--> 180     r = func(*args, **kwargs)
    181     time_spent = time.time() - t0
    182 # print(f"Dynamo timer: key={key}, latency={latency:.2f} sec")

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py:515, in _compile(code, globals, locals, builtins, compiler_fn, one_graph, export, export_constraints, hooks, frame, frame_state)
    513 except Exception as e:
    514     exception_handler(e, code, frame)
--> 515     raise InternalTorchDynamoError(str(e)).with_traceback(e.__traceback__) from None

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py:478, in _compile(code, globals, locals, builtins, compiler_fn, one_graph, export, export_constraints, hooks, frame, frame_state)
    476 assert output.guards is not None
    477 CleanupManager.instance[out_code] = output.cleanups
--> 478 check_fn = CheckFunctionManager(
    479     output,
    480     locals,
    481     globals,
    482     hooks.guard_fail_fn if hooks else None,
    483 )
    485 guarded_code = GuardedCode(out_code, check_fn.check_fn)
    487 if guards_log.isEnabledFor(logging.DEBUG):

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/guards.py:865, in CheckFunctionManager.__init__(self, output_graph, f_locals, f_globals, guard_fail_fn)
    855     if (
    856         not config.guard_nn_modules
    857         and guard.is_nn_module()
   (...)
    862         and (config.skip_nnmodule_hook_guards or "hooks" not in guard.name)
    863     ):
    864         continue
--> 865     guard.create(local_builder, global_builder)
    866 self.check_fn = self.compile_check_fn(
    867     local_builder, global_builder, guards, guard_fail_fn
    868 )
    869 self._seen_ids.clear()

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_guards.py:208, in Guard.create(self, local_builder, global_builder)
    207 def create(self, local_builder: GuardBuilderBase, global_builder: GuardBuilderBase):
--> 208     return self.create_fn(self.source.select(local_builder, global_builder), self)

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/guards.py:224, in GuardBuilder.TYPE_MATCH(self, guard)
    222 def TYPE_MATCH(self, guard: Guard):
    223     # ___check_type_id is same as `id(type(x)) == y`
--> 224     t = type(self.get(guard.name))
    225     obj_id = self.id_ref(t)
    226     code = f"___check_type_id({self.arg_ref(guard)}, {obj_id})"

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/guards.py:200, in GuardBuilder.get(self, name)
    199 def get(self, name: str) -> Any:
--> 200     return eval(name, self.scope, CLOSURE_VARS)

File <string>:1

InternalTorchDynamoError: name 'L' is not defined


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Comment by ev-br** [comment]
Trying to distill an MWE:

```
In [50]: @torch.compile
    ...: def h(x):
    ...:     a = x**2
    ...:     b = tnp.linspace(0, 1, 11, dtype=tnp.float64)
    ...:     c = a + b
    ...:     return c
    ...: 

In [51]: h(tnp.ones(11))
---------------------------------------------------------------------------
InternalTorchDynamoError                  Traceback (most recent call last)
Cell In[51], line 1
----> 1 h(tnp.ones(11))

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py:295, in _TorchDynamoContext.__call__.<locals>._fn(*args, **kwargs)
    293 dynamic_ctx.__enter__()
    294 try:
--> 295     return fn(*args, **kwargs)
    296 finally:
    297     set_eval_frame(prior)

Cell In[50], line 5, in h(x)
      3 a = x**2 
      4 b = tnp.linspace(0, 1, 11, dtype=tnp.float64)
----> 5 c = a + b
      6 return c
```

**Comment by ezyang** [comment]
@larryliu0820 are you able to look into this?

**Comment by larryliu0820** [comment]
I can take a look after I finish my current work of supporting ndarray methods in dynamo. @lezcano mentioned it’s important to have method support

**Comment by larryliu0820** [comment]
> In [56]: h1(tnp.ones(11))

What's happening here? Are you feeding torch_np.ndarray as an argument (which I think is not allowed)? Can you paste the full repro steps as well?

**Comment by larryliu0820** [comment]
Pretty amazing this actually works lol. Good it's resolved!

**Comment by ev-br** [comment]
Indeed, great work! 
Will test it more, will report issues if there any. BTW, how to check compilation results, is there a switch to see the generated IR, also see if there are graph breaks? (%timeit results are identical with and without compile, makes me wonder what's going on)

**Comment by ev-br** [comment]
Indeed. First, running the example without importing numpy fails; With numpy imported, the output is

```
In [4]: import numpy as np

In [5]: @torch.compile
   ...:     ...: def mandelbrot_tnumpy(max_iter=200):
   ...:     ...:     # Define the boundaries of the complex plane
   ...:     ...:     xn = 450
   ...:     ...:     yn = 375
   ...:     ...:     xmin = -2.25
   ...:     ...:     xmax = 0.75
   ...:     ...:     ymin = -1.25
   ...:     ...:     ymax = 1.25
   ...:     ...:
   ...:     ...:     # Create the grid of complex numbers
   ...:     ...:     x_values = np.linspace(xmin, xmax, xn, dtype=float)
   ...:     ...:     y_values = np.linspace(ymin, ymax, yn, dtype=float)
   ...:     ...:     rx, iy = np.meshgrid(x_values, y_values, indexing='xy')
   ...:     ...:
   ...:     ...:     x = rx.copy()
   ...:     ...:     y = iy.copy()
   ...:     ...:     mask = np.zeros_like(x)
   ...:     ...:     for i in range(max_iter):
   ...:     ...:         x_prev = x
   ...:     ...:         y_prev = y
   ...:     ...:         x = x_prev**2 - y_prev**2 + rx
   ...:     ...:         y = 2*x_prev*y_prev + iy
   ...:     ...:         inside = np.sqrt(x**2 + y**2) <= 2
   ...:     ...:         mask+=inside
   ...:     ...:     return mask
   ...: 

In [6]: mandelbrot_tnumpy()
[2023-06-12 22:39:28,805] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing mandelbrot_tnumpy <ipython-input-5-9f426bdbf400>:1
[2023-06-12 22:39:28,806] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-5-9f426bdbf400>:4
[2023-06-12 22:39:28,806] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 450 []
[2023-06-12 22:39:28,806] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST xn [ConstantVariable(int)]
[2023-06-12 22:39:28,806] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-5-9f426bdbf400>:5
[2023-06-12 22:39:28,806] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 375 []
[2023-06-12 22:39:28,806] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST yn [ConstantVariable(int)]
[2023-06-12 22:39:28,807] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-5-9f426bdbf400>:6
[2023-06-12 22:39:28,807] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST -2.25 []
[2023-06-12 22:39:28,807] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST xmin [ConstantVariable(float)]
[2023-06-12 22:39:28,807] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-5-9f426bdbf400>:7
[2023-06-12 22:39:28,807] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 0.75 []
[2023-06-12 22:39:28,807] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST xmax [ConstantVariable(float)]
[2023-06-12 22:39:28,807] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-5-9f426bdbf400>:8
[2023-06-12 22:39:28,808] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST -1.25 []
[2023-06-12 22:39:28,808] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST ymin [ConstantVariable(float)]
[2023-06-12 22:39:28,808] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-5-9f426bdbf400>:9
[2023-06-12 22:39:28,808] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 1.25 []
[2023-06-12 22:39:28,808] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST ymax [ConstantVariable(float)]
[2023-06-12 22:39:28,808] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-5-9f426bdbf400>:12
[2023-06-12 22:39:28,808] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL np []
[2023-06-12 22:39:28,809] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR linspace [PythonModuleVariable()]
[2023-06-12 22:39:28,810] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST xmin [NumpyVariable()]
[2023-06-12 22:39:28,810] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST xmax [NumpyVariable(), ConstantVariable(float)]
[2023-06-12 22:39:28,811] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST xn [NumpyVariable(), ConstantVariable(float), ConstantVariable(float)]
[2023-06-12 22:39:28,811] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL float [NumpyVariable(), ConstantVariable(float), ConstantVariable(float), ConstantVariable(int)]
[2023-06-12 22:39:28,811] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST ('dtype',) [NumpyVariable(), ConstantVariable(float), ConstantVariable(float), ConstantVariable(int), BuiltinVariable(float)]
[2023-06-12 22:39:28,811] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION_KW 4 [NumpyVariable(), ConstantVariable(float), ConstantVariable(float), ConstantVariable(int), BuiltinVariable(float), ConstantVariable(tuple)]
[2023-06-12 22:39:28,811] torch._dynamo.symbolic_convert: [DEBUG] break_graph_if_unsupported triggered compile
Traceback (most recent call last):
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 389, in wrapper
    return inner_fn(self, inst)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1151, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 558, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 797, in call_function
    unimplemented(f"numpy.{self.value}()")
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 135, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: numpy.<function linspace at 0x7ffa9c0b4160>()
[2023-06-12 22:39:28,819] torch._dynamo.output_graph: [DEBUG] restore_graphstate: removed 0 nodes
[2023-06-12 22:39:28,819] torch._dynamo.output_graph: [DEBUG] COMPILING GRAPH due to GraphCompileReason(reason='numpy.<function linspace at 0x7ffa9c0b4160>()', user_stack=[<FrameSummary file <ipython-input-5-9f426bdbf400>, line 12 in mandelbrot_tnumpy>], graph_break=True)
[2023-06-12 22:39:28,834] torch._dynamo.convert_frame.__guards: [DEBUG] GUARDS:
  ___is_grad_enabled()
  not ___are_deterministic_algorithms_enabled()
  utils_device.CURRENT_DEVICE == None
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping linspace <__array_function__ internals>
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping _linspace_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/function_base.py
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping linspace /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/function_base.py
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping result_type <__array_function__ internals>
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping result_type /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/multiarray.py
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping issubdtype /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numerictypes.py
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping issubclass_ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numerictypes.py
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping ndim <__array_function__ internals>
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping _ndim_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/fromnumeric.py
[2023-06-12 22:39:28,835] torch._dynamo.eval_frame: [DEBUG] skipping ndim /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/fromnumeric.py
[2023-06-12 22:39:28,836] torch._dynamo.eval_frame: [DEBUG] skipping isscalar /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numeric.py
[2023-06-12 22:39:28,836] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* <resume in mandelbrot_tnumpy>             <ipython-input-5-9f426bdbf400> 12
[2023-06-12 22:39:28,836] torch._dynamo.eval_frame: [DEBUG] skipping meshgrid <__array_function__ internals>
[2023-06-12 22:39:28,836] torch._dynamo.eval_frame: [DEBUG] skipping _meshgrid_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:39:28,836] torch._dynamo.eval_frame: [DEBUG] skipping meshgrid /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:39:28,836] torch._dynamo.eval_frame: [DEBUG] skipping <listcomp> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:39:28,836] torch._dynamo.eval_frame: [DEBUG] skipping broadcast_arrays <__array_function__ internals>
[2023-06-12 22:39:28,836] torch._dynamo.eval_frame: [DEBUG] skipping _broadcast_arrays_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:39:28,836] torch._dynamo.eval_frame: [DEBUG] skipping broadcast_arrays /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:39:28,836] torch._dynamo.eval_frame: [DEBUG] skipping <listcomp> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:39:28,837] torch._dynamo.eval_frame: [DEBUG] skipping _broadcast_shape /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:39:28,837] torch._dynamo.eval_frame: [DEBUG] skipping <genexpr> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:39:28,837] torch._dynamo.eval_frame: [DEBUG] skipping <listcomp> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:39:28,837] torch._dynamo.eval_frame: [DEBUG] skipping _broadcast_to /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:39:28,837] torch._dynamo.eval_frame: [DEBUG] skipping iterable /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:39:28,837] torch._dynamo.eval_frame: [DEBUG] skipping <genexpr> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:39:28,837] torch._dynamo.eval_frame: [DEBUG] skipping _maybe_view_as_subclass /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:39:28,837] torch._dynamo.eval_frame: [DEBUG] skipping <listcomp> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:39:28,840] torch._dynamo.eval_frame: [DEBUG] skipping zeros_like <__array_function__ internals>
[2023-06-12 22:39:28,840] torch._dynamo.eval_frame: [DEBUG] skipping _zeros_like_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numeric.py
[2023-06-12 22:39:28,840] torch._dynamo.eval_frame: [DEBUG] skipping zeros_like /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numeric.py
[2023-06-12 22:39:28,840] torch._dynamo.eval_frame: [DEBUG] skipping empty_like <__array_function__ internals>
[2023-06-12 22:39:28,840] torch._dynamo.eval_frame: [DEBUG] skipping empty_like /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/multiarray.py
[2023-06-12 22:39:28,841] torch._dynamo.eval_frame: [DEBUG] skipping copyto <__array_function__ internals>
[2023-06-12 22:39:28,841] torch._dynamo.eval_frame: [DEBUG] skipping copyto /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/multiarray.py
[2023-06-12 22:39:28,867] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* __init__             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 403
[2023-06-12 22:39:28,867] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* _showwarnmsg             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 96
[2023-06-12 22:39:28,867] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* _showwarnmsg_impl             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 20
[2023-06-12 22:39:28,868] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* _formatwarnmsg             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 117
[2023-06-12 22:39:28,868] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* _formatwarnmsg_impl             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 35
[2023-06-12 22:39:28,868] torch._dynamo.eval_frame: [DEBUG] skipping getline /home/br/mambaforge/envs/torch_nightly/lib/python3.8/linecache.py
[2023-06-12 22:39:28,868] torch._dynamo.eval_frame: [DEBUG] skipping getlines /home/br/mambaforge/envs/torch_nightly/lib/python3.8/linecache.py
<ipython-input-5-9f426bdbf400>:24: RuntimeWarning: overflow encountered in square
  inside = np.sqrt(x**2 + y**2) <= 2
<ipython-input-5-9f426bdbf400>:24: RuntimeWarning: overflow encountered in square
  inside = np.sqrt(x**2 + y**2) <= 2
<ipython-input-5-9f426bdbf400>:24: RuntimeWarning: overflow encountered in add
  inside = np.sqrt(x**2 + y**2) <= 2
<ipython-input-5-9f426bdbf400>:22: RuntimeWarning: overflow encountered in square
  x = x_prev**2 - y_prev**2 + rx
<ipython-input-5-9f426bdbf400>:22: RuntimeWarning: invalid value encountered in subtract
  x = x_prev**2 - y_prev**2 + rx
<ipython-input-5-9f426bdbf400>:23: RuntimeWarning: overflow encountered in multiply
  y = 2*x_prev*y_prev + iy
<ipython-input-5-9f426bdbf400>:23: RuntimeWarning: invalid value encountered in multiply
  y = 2*x_prev*y_prev + iy
Out[6]: 
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])
```

This is with 

```
(torch_nightly) br@gonzales:~/sweethome/proj/scipy/torch_np_compat$ echo $TORCHDYNAMO_VERBOSE
1
(torch_nightly) br@gonzales:~/sweethome/proj/scipy/torch_np_compat$ echo $TORCH_LOGS
+dynamo
```

**Comment by larryliu0820** [comment]
Ok can you create a different issue with the repro steps? I can take a look

**Comment by ev-br** [comment]
Here it is, https://github.com/Quansight-Labs/numpy_pytorch_interop/issues/159
