### ISSUE TITLE
@torch.compile does not compile 

### ISSUE THREAD

**Issue by ev-br** [Quansight-Labs/numpy_pytorch_interop#159]
```
$ export TORCH_LOGS="+dynamo"
$ export TORCHDYNAMO_VERBOSE=1
$ ipython
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: import numpy as np

In [3]: @torch.compile
   ...:     ...: def mandelbrot_tnumpy(max_iter=200):
   ...:     ...:     # Define the boundaries of the complex plane
   ...:     ...:     xn = 450
   ...:     ...:     yn = 375
   ...:     ...:     xmin = -2.25
   ...:     ...:     xmax = 0.75
   ...:     ...:     ymin = -1.25
   ...:     ...:     ymax = 1.25
   ...:     ...:
   ...:     ...:     # Create the grid of complex numbers
   ...:     ...:     x_values = np.linspace(xmin, xmax, xn, dtype=float)
   ...:     ...:     y_values = np.linspace(ymin, ymax, yn, dtype=float)
   ...:     ...:     rx, iy = np.meshgrid(x_values, y_values, indexing='xy')
   ...:     ...:
   ...:     ...:     x = rx.copy()
   ...:     ...:     y = iy.copy()
   ...:     ...:     mask = np.zeros_like(x)
   ...:     ...:     for i in range(max_iter):
   ...:     ...:         x_prev = x
   ...:     ...:         y_prev = y
   ...:     ...:         x = x_prev**2 - y_prev**2 + rx
   ...:     ...:         y = 2*x_prev*y_prev + iy
   ...:     ...:         inside = np.sqrt(x**2 + y**2) <= 2
   ...:     ...:         mask+=inside
   ...:     ...:     return mask
   ...: 

In [4]: mandelbrot_tnumpy()
[2023-06-12 22:47:26,095] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-06-12 22:47:26,096] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-06-12 22:47:26,096] torch._dynamo.eval_frame: [DEBUG] skipping __init__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-06-12 22:47:26,096] torch._dynamo.eval_frame: [DEBUG] skipping __enter__ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/contextlib.py
[2023-06-12 22:47:26,096] torch._dynamo.eval_frame: [DEBUG] skipping enable_dynamic /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py
[2023-06-12 22:47:26,097] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing mandelbrot_tnumpy <ipython-input-3-9f426bdbf400>:1
[2023-06-12 22:47:26,099] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-3-9f426bdbf400>:4
[2023-06-12 22:47:26,099] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 450 []
[2023-06-12 22:47:26,099] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST xn [ConstantVariable(int)]
[2023-06-12 22:47:26,099] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-3-9f426bdbf400>:5
[2023-06-12 22:47:26,099] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 375 []
[2023-06-12 22:47:26,099] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST yn [ConstantVariable(int)]
[2023-06-12 22:47:26,099] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-3-9f426bdbf400>:6
[2023-06-12 22:47:26,099] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST -2.25 []
[2023-06-12 22:47:26,100] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST xmin [ConstantVariable(float)]
[2023-06-12 22:47:26,100] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-3-9f426bdbf400>:7
[2023-06-12 22:47:26,100] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 0.75 []
[2023-06-12 22:47:26,100] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST xmax [ConstantVariable(float)]
[2023-06-12 22:47:26,100] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-3-9f426bdbf400>:8
[2023-06-12 22:47:26,100] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST -1.25 []
[2023-06-12 22:47:26,100] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST ymin [ConstantVariable(float)]
[2023-06-12 22:47:26,100] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-3-9f426bdbf400>:9
[2023-06-12 22:47:26,100] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST 1.25 []
[2023-06-12 22:47:26,101] torch._dynamo.symbolic_convert: [DEBUG] TRACE STORE_FAST ymax [ConstantVariable(float)]
[2023-06-12 22:47:26,101] torch._dynamo.symbolic_convert: [DEBUG] TRACE starts_line <ipython-input-3-9f426bdbf400>:12
[2023-06-12 22:47:26,101] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL np []
[2023-06-12 22:47:26,102] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_ATTR linspace [PythonModuleVariable()]
[2023-06-12 22:47:26,103] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST xmin [NumpyVariable()]
[2023-06-12 22:47:26,103] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST xmax [NumpyVariable(), ConstantVariable(float)]
[2023-06-12 22:47:26,103] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_FAST xn [NumpyVariable(), ConstantVariable(float), ConstantVariable(float)]
[2023-06-12 22:47:26,103] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_GLOBAL float [NumpyVariable(), ConstantVariable(float), ConstantVariable(float), ConstantVariable(int)]
[2023-06-12 22:47:26,103] torch._dynamo.symbolic_convert: [DEBUG] TRACE LOAD_CONST ('dtype',) [NumpyVariable(), ConstantVariable(float), ConstantVariable(float), ConstantVariable(int), BuiltinVariable(float)]
[2023-06-12 22:47:26,103] torch._dynamo.symbolic_convert: [DEBUG] TRACE CALL_FUNCTION_KW 4 [NumpyVariable(), ConstantVariable(float), ConstantVariable(float), ConstantVariable(int), BuiltinVariable(float), ConstantVariable(tuple)]
[2023-06-12 22:47:26,103] torch._dynamo.symbolic_convert: [DEBUG] break_graph_if_unsupported triggered compile
Traceback (most recent call last):
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 389, in wrapper
    return inner_fn(self, inst)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1151, in CALL_FUNCTION_KW
    self.call_function(fn, args, kwargs)
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 558, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/variables/misc.py", line 797, in call_function
    unimplemented(f"numpy.{self.value}()")
  File "/home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/_dynamo/exc.py", line 135, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: numpy.<function linspace at 0x7f5ad418e160>()
[2023-06-12 22:47:26,105] torch._dynamo.output_graph: [DEBUG] restore_graphstate: removed 0 nodes
[2023-06-12 22:47:26,105] torch._dynamo.output_graph: [DEBUG] COMPILING GRAPH due to GraphCompileReason(reason='numpy.<function linspace at 0x7f5ad418e160>()', user_stack=[<FrameSummary file <ipython-input-3-9f426bdbf400>, line 12 in mandelbrot_tnumpy>], graph_break=True)
[2023-06-12 22:47:26,132] torch._dynamo.convert_frame.__guards: [DEBUG] GUARDS:
  ___is_grad_enabled()
  not ___are_deterministic_algorithms_enabled()
  utils_device.CURRENT_DEVICE == None
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping linspace <__array_function__ internals>
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping _linspace_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/function_base.py
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping linspace /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/function_base.py
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping result_type <__array_function__ internals>
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping result_type /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/multiarray.py
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping issubdtype /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numerictypes.py
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping issubclass_ /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numerictypes.py
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping ndim <__array_function__ internals>
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping _ndim_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/fromnumeric.py
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping ndim /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/fromnumeric.py
[2023-06-12 22:47:26,132] torch._dynamo.eval_frame: [DEBUG] skipping isscalar /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numeric.py
[2023-06-12 22:47:26,133] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* <resume in mandelbrot_tnumpy>             <ipython-input-3-9f426bdbf400> 12
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping meshgrid <__array_function__ internals>
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping _meshgrid_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping meshgrid /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping <listcomp> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping broadcast_arrays <__array_function__ internals>
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping _broadcast_arrays_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping broadcast_arrays /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping <listcomp> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping _broadcast_shape /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping <genexpr> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping <listcomp> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping _broadcast_to /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping iterable /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping <genexpr> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping _maybe_view_as_subclass /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/stride_tricks.py
[2023-06-12 22:47:26,133] torch._dynamo.eval_frame: [DEBUG] skipping <listcomp> /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/lib/function_base.py
[2023-06-12 22:47:26,135] torch._dynamo.eval_frame: [DEBUG] skipping zeros_like <__array_function__ internals>
[2023-06-12 22:47:26,136] torch._dynamo.eval_frame: [DEBUG] skipping _zeros_like_dispatcher /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numeric.py
[2023-06-12 22:47:26,136] torch._dynamo.eval_frame: [DEBUG] skipping zeros_like /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/numeric.py
[2023-06-12 22:47:26,136] torch._dynamo.eval_frame: [DEBUG] skipping empty_like <__array_function__ internals>
[2023-06-12 22:47:26,136] torch._dynamo.eval_frame: [DEBUG] skipping empty_like /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/multiarray.py
[2023-06-12 22:47:26,136] torch._dynamo.eval_frame: [DEBUG] skipping copyto <__array_function__ internals>
[2023-06-12 22:47:26,136] torch._dynamo.eval_frame: [DEBUG] skipping copyto /home/br/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/numpy/core/multiarray.py
[2023-06-12 22:47:26,158] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* __init__             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 403
[2023-06-12 22:47:26,158] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* _showwarnmsg             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 96
[2023-06-12 22:47:26,158] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* _showwarnmsg_impl             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 20
[2023-06-12 22:47:26,159] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* _formatwarnmsg             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 117
[2023-06-12 22:47:26,159] torch._dynamo.convert_frame: [DEBUG] skipping because no torch.* _formatwarnmsg_impl             /home/br/mambaforge/envs/torch_nightly/lib/python3.8/warnings.py 35
[2023-06-12 22:47:26,159] torch._dynamo.eval_frame: [DEBUG] skipping getline /home/br/mambaforge/envs/torch_nightly/lib/python3.8/linecache.py
[2023-06-12 22:47:26,159] torch._dynamo.eval_frame: [DEBUG] skipping getlines /home/br/mambaforge/envs/torch_nightly/lib/python3.8/linecache.py
<ipython-input-3-9f426bdbf400>:24: RuntimeWarning: overflow encountered in square
  inside = np.sqrt(x**2 + y**2) <= 2
<ipython-input-3-9f426bdbf400>:24: RuntimeWarning: overflow encountered in square
  inside = np.sqrt(x**2 + y**2) <= 2
<ipython-input-3-9f426bdbf400>:24: RuntimeWarning: overflow encountered in add
  inside = np.sqrt(x**2 + y**2) <= 2
<ipython-input-3-9f426bdbf400>:22: RuntimeWarning: overflow encountered in square
  x = x_prev**2 - y_prev**2 + rx
<ipython-input-3-9f426bdbf400>:22: RuntimeWarning: invalid value encountered in subtract
  x = x_prev**2 - y_prev**2 + rx
<ipython-input-3-9f426bdbf400>:23: RuntimeWarning: overflow encountered in multiply
  y = 2*x_prev*y_prev + iy
<ipython-input-3-9f426bdbf400>:23: RuntimeWarning: invalid value encountered in multiply
  y = 2*x_prev*y_prev + iy
Out[4]: 
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]: torch.__version__
Out[5]: '2.1.0.dev20230610+cpu'
```

cc @larryliu0820

**Comment by larryliu0820** [comment]
I can take a look

**Comment by larryliu0820** [comment]
can you do `@torch.compile(numpy_ndarray_as_tensor=True)`

**Comment by ev-br** [comment]
> can you do @torch.compile(numpy_ndarray_as_tensor=True)

```
TypeError: compile() got an unexpected keyword argument 'numpy_ndarray_as_tensor'

In [3]: torch.__version__
Out[3]: '2.1.0.dev20230612+cpu'
```

**Comment by larryliu0820** [comment]
@ezyang I don't think we currently support int input to the graph, right? What is the workaround for this?

**Comment by ezyang** [comment]
Do torch._dynamo.config.numpy_ndarray_as_tensor = True instead

**Comment by ev-br** [comment]
```
In [1]: import torch

In [2]: torch.__version__
Out[2]: '2.1.0.dev20230612+cpu'

In [3]: torch._dynamo
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 torch._dynamo

File ~/mambaforge/envs/torch_nightly/lib/python3.8/site-packages/torch/__init__.py:1724, in __getattr__(name)
   1722     warnings.warn(f"'{name}' is deprecated, please use '{replacement.__module__}.{replacement.__name__}()'", stacklevel=2)
   1723     return replacement()
-> 1724 raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

AttributeError: module 'torch' has no attribute '_dynamo'
```

**Comment by larryliu0820** [comment]
`import torch._dynamo`. Also probably need to patch these two PRs: https://github.com/pytorch/pytorch/pull/103457 and https://github.com/pytorch/pytorch/pull/103546. Then it still ran into some issue. At least it can go much further with those 2 PRs.

**Comment by ev-br** [comment]
Thanks @larryliu0820. I see now that https://github.com/pytorch/pytorch/pull/103546 includes the OP snippet from this PR. Am looking forward for pytorch PRs to land so that I can test it further!

**Comment by larryliu0820** [comment]
@ev-br just a heads up, once we have https://github.com/pytorch/pytorch/pull/103546 merged this code snippet should be able to use @torch.compile. Please try it out then.

**Comment by ev-br** [comment]
https://github.com/Quansight-Labs/numpy_pytorch_interop/pull/161 sidesteps the dtype issue by using `dtype="float64"` strings explicitly. That said, using `dtype=np.float64` is both idiomatic and widespread.

**Comment by lezcano** [comment]
Closign this one, but @larryliu0820 let's try to get https://github.com/pytorch/pytorch/pull/103546 merged soon so that it eases our testing of the integration.
