### ISSUE TITLE
Should not create tensor on import

### ISSUE THREAD

**Issue by ezyang** [Quansight-Labs/numpy_pytorch_interop#166]
This program

```
import torch
import torch.nn as nn
from torch.fx.experimental.proxy_tensor import make_fx
#from torch.profiler import profile, record_function, ProfilerActivity

#with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as prof:
embedding_sum = nn.EmbeddingBag(10, 3, mode='sum')
input = torch.tensor([1, 2, 4, 5, 4, 3, 2, 9], dtype=torch.long)
offsets = torch.tensor([0, 4], dtype=torch.long)

def f(input, offsets):
    r = embedding_sum(input, offsets)
    r.sum().backward()
    return embedding_sum.weight.grad

make_fx(f)(input, offsets).print_readable()
```

fails with

```
(/home/ezyang/local/d/pytorch-env) [ezyang@devgpu019.ftw1 ~/local/d/pytorch (5cd861fc)]$ python test.py
Traceback (most recent call last):
  File "/data/users/ezyang/d/pytorch/test.py", line 16, in <module>
    make_fx(f)(input, offsets).print_readable()
  File "/data/users/ezyang/d/pytorch/torch/fx/experimental/proxy_tensor.py", line 809, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_dispatch), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/data/users/ezyang/d/pytorch/torch/_compile.py", line 22, in inner
    import torch._dynamo
  File "/data/users/ezyang/d/pytorch/torch/_dynamo/__init__.py", line 1, in <module>
    from . import allowed_functions, convert_frame, eval_frame, resume_execution
  File "/data/users/ezyang/d/pytorch/torch/_dynamo/allowed_functions.py", line 18, in <module>
    from .utils import HAS_NUMPY, is_safe_constant, np
  File "/data/users/ezyang/d/pytorch/torch/_dynamo/utils.py", line 42, in <module>
    import torch_np
  File "/data/users/ezyang/d/numpy_pytorch_interop/torch_np/__init__.py", line 27, in <module>
    False_ = asarray(False, bool_)
  File "/data/users/ezyang/d/numpy_pytorch_interop/torch_np/_ndarray.py", line 511, in asarray
    return array(a, dtype=dtype, order=order, like=like, copy=False, ndmin=0)
  File "/data/users/ezyang/d/numpy_pytorch_interop/torch_np/_ndarray.py", line 506, in array
    tensor = _util._coerce_to_tensor(obj, torch_dtype, copy, ndmin)
  File "/data/users/ezyang/d/numpy_pytorch_interop/torch_np/_util.py", line 197, in _coerce_to_tensor
    tensor = torch.as_tensor(obj)
  File "/data/users/ezyang/d/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/data/users/ezyang/d/pytorch/torch/fx/experimental/proxy_tensor.py", line 555, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/data/users/ezyang/d/pytorch/torch/fx/experimental/proxy_tensor.py", line 580, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_dispatch, args, kwargs)
  File "/data/users/ezyang/d/pytorch/torch/fx/experimental/proxy_tensor.py", line 347, in proxy_call
    name=proxy_mode.tracer.graph._target_to_str(func.overloadpacket.__name__))
AttributeError: 'PythonKeyTracer' object has no attribute 'graph'
```

The reason is that when we lazily do the `torch_np` import, it calls a torch tensor operation, which breaks because at this time we have already installed the `make_fx` interception. The correct thing to do is NOT eagerly call tensor operations on import.

**Comment by lezcano** [comment]
Let's just simpyl remove those constants for now @ev-br
